### ISSUE TITLE
optimal_parameter_intervention_for_maximum_threshold

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/EasyModelAnalysis.jl#132]
Similar to `optimal_parameter_intervention_for_threshold`, but makes sure the maximum over the entire interval is below the threshold. For example, optimize intervention parameters such that the maximum of infections is below 0.33 while getting the minimum intervention cost.

**Comment by YingboMa** [comment]
`optimal_parameter_intervention_for_threshold` already does that.
