### ISSUE TITLE
Add a simple datafit command

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/EasyModelAnalysis.jl#14]
Just L2 against some given dataset, remake the prob to match the time. Take in `t` and `data`?

**Comment by ArnoStrouwen** [comment]
Assume all states or a subset?

**Comment by ChrisRackauckas** [comment]
Assume a subset. `t = [0.0,1.0,2.0], data = [x => [3.0,4.0,5.0], z => [2.0,5.0,7.0]]`. Add `missing` support later?
