### ISSUE TITLE
ensemble simulation of a collection of MTK models

### ISSUE THREAD

**Issue by anandijain** [SciML/EasyModelAnalysis.jl#148]
simple function that solves a bunch of MTK models. 
related to covid forecast hub task.

i can't assign but this is on me

**Comment by anandijain** [comment]
i guess part of it may be non-uniformity in state names of the model collection

**Comment by ChrisRackauckas** [comment]
What is needed beyond https://github.com/SciML/EasyModelAnalysis.jl/blob/main/src/basics.jl#L85-L132 and https://github.com/SciML/EasyModelAnalysis.jl/blob/4ffafdb580e4d8f28dbb35e7af166a0baef85e09/src/datafit.jl#L122-L145 ?
